name: C/C++ CI TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: g++ version
      run: g++ -v
    - name: build
      run: g++ -o test.exe test.cpp
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
         name: test
         path: test.exe