name: C/C++ CI TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_win:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name:  test
        run: cmake --version

      - name: cmake
        run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: cmake --build build  

      # - name: Setup CMake
      #   uses: lukka/get-cmake@latest

      # - name: Setup Dependencies Windows
      #   uses: msys2/setup-msys2@v2
      #   with:
      #     update: true
      #     install: >-
      #       base-devel
      #       diffutils
      #       git
      #       make
      #       mingw-w64-x86_64-binutils
      #       mingw-w64-x86_64-boost
      #       mingw-w64-x86_64-cmake
      #       mingw-w64-x86_64-curl
      #       mingw-w64-x86_64-libmfx
      #       mingw-w64-x86_64-nsis
      #       mingw-w64-x86_64-openssl
      #       mingw-w64-x86_64-opus
      #       mingw-w64-x86_64-toolchain
      #       nasm
      #       wget
      #       yasm


      # - name: Build Windows
      #   shell: msys2 {0}
      #   run: g++ -v
      # - name: build
      #   run: g++ -o test.exe test.cpp


      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
         name: test
         path: .\build\**\*.exe
